import type { TreeLeaf, TreeNode, HobbyItem } from '@/types/tree';
export type { TreeLeaf, TreeNode, HobbyItem };
export { isLeaf, getFirstLeaf } from '@/types/tree';

// ─── Personal ────────────────────────────────────────────────────────────────

export const personalTree: TreeNode[] = [
  {
    id: 'personal-info',
    label: 'personal-info',
    children: [
      {
        id: 'bio',
        label: 'bio',
        children: [
          {
            id: 'bio-ts',
            label: 'bio.ts',
            content: [
              '// Atuo na área de desenvolvimento de software desde 2018,',
              '// com quase 8 anos de experiência em projetos de médio',
              '// e grande porte.',
              '//',
              '// Ao longo da minha trajetória, participei de iniciativas',
              '// relevantes em empresas como Sicredi, Natura, Cielo',
              '// e Grupo DPSP.',
              '//',
              '// Tenho sólida experiência no desenvolvimento de aplicações',
              '// frontend modernas, com foco em React, TypeScript,',
              '// performance e escalabilidade.',
              '//',
              '// Também possuo experiência com integrações de APIs,',
              '// arquitetura de aplicações, testes automatizados e',
              '// boas práticas de engenharia de software.',
              '//',
              '// Minha atuação principal é em frontend, com experiência',
              '// complementar em backend e aplicações mobile, sempre',
              '// contribuindo com soluções robustas e evolutivas.',
              '',
              '',
              '',
              'const bio = {',
              "  name: 'Thiago Bergenthal de Borba',",
              "  role: 'Senior Front-end Developer',",
              "  experience: '~8 years (since 2018)',",
              "  location: 'Gravataí, RS, Brazil',",
              "  languages: ['Portuguese (native)', 'English (intermediate)'],",
              "  contact: 'thiagoborbadev@gmail.com',",
              '};',
            ],
          },
        ],
      },
      {
        id: 'expertise',
        label: 'expertise',
        children: [
          {
            id: 'expertise-ts',
            label: 'expertise.ts',
            content: [
              'const expertise = [',
              "  'TypeScript',",
              "  'JavaScript (ES6+)',",
              "  'React.js',",
              "  'Next.js',",
              "  'Node.js',",
              "  'React Native',",
              "  'MobX',",
              "  'GraphQL',",
              "  'REST APIs',",
              "  'Micro front-ends',",
              "  'React Testing Library',",
              "  'Vitest',",
              "  'Jest',",
              "  'GitLab CI/CD',",
              "  'Git',",
              "  'Accessibility',",
              "  'Performance',",
              "  'Design Systems',",
              "  'MongoDB',",
              '];',
            ],
          },
        ],
      },
      {
        id: 'education',
        label: 'education',
        children: [
          {
            id: 'tech-admin',
            label: 'technical-degree.ts',
            content: [
              'const technicalDegree = {',
              "  course: 'Técnico em Administração',",
              "  status: 'concluded',",
              "  year: '2012',",
              '};',
            ],
          },
          {
            id: 'ads',
            label: 'systems-analysis.ts',
            content: [
              'const systemsAnalysis = {',
              "  course: 'Análise e Desenvolvimento de Sistemas',",
              "  institution: 'Unisinos',",
              "  period: '06/2018 – 06/2020',",
              "  status: 'incomplete',",
              '};',
            ],
          },
        ],
      },
      {
        id: 'experience',
        label: 'experience',
        children: [
          {
            id: 'dbc',
            label: 'dbc-company.ts',
            content: [
              'const dbcCompany = {',
              "  company: 'DBC Company / Grupo DPSP',",
              "  role: 'Senior Developer',",
              "  period: '01/2025 – 04/2026',",
              "  project: 'Balcão 2.0 — Drogaria São Paulo',",
              "  stack: ['React.js', 'TypeScript', 'MobX', 'GitLab CI'],",
              '  highlights: [',
              "    'React + TypeScript em aplicação de alto volume',",
              "    'Gerenciamento de estado com MobX',",
              "    'Integração com APIs e fluxos complexos de negócio',",
              "    'Testes com React Testing Library',",
              "    'Lazy loading e code splitting para performance',",
              "    'Redução de re-renderizações e otimização de render',",
              "    'CI/CD com GitLab e automação de deploys',",
              "    'Deploy em produção com acompanhamento pós-deploy',",
              "    'Monitoramento e correção de incidentes em produção',",
              "    'Code review e padronização de arquitetura frontend',",
              "    'Implementação de proteção contra clickjacking',",
              '  ],',
              '};',
            ],
          },
          {
            id: 'marketdata',
            label: 'marketdata-solutions.ts',
            content: [
              'const marketdata = {',
              "  company: 'Marketdata Solutions Brasil',",
              "  role: 'Development Analyst',",
              "  period: '05/2023 – 01/2025',",
              "  clients: ['Cielo', 'Natura', 'Financial market client'],",
              "  stack: ['React.js', 'TypeScript', 'Next.js', 'ASP.NET', 'AngularJS'],",
              '  highlights: [',
              "    'Desenvolvimento com React e TypeScript',",
              "    'Next.js com SSR e integração com APIs',",
              "    'Manutenção de aplicações ASP.NET e AngularJS',",
              "    'Integração frontend com APIs REST',",
              "    'Adaptação entre múltiplas stacks e arquiteturas',",
              '  ],',
              '};',
            ],
          },
          {
            id: 'iteris',
            label: 'iteris.ts',
            content: [
              'const iteris = {',
              "  company: 'Iteris Consultoria e Software',",
              "  role: 'Software Engineer',",
              "  period: '08/2022 – 05/2023',",
              "  project: 'Plataforma digital Nutrien — squad Solicitação de Crédito',",
              "  stack: ['React', 'TypeScript', 'Apollo GraphQL', 'React Hook Form', 'i18next'],",
              '  highlights: [',
              "    'React com TypeScript em formulários complexos',",
              "    'Gerenciamento de dados com GraphQL (Apollo)',",
              "    'React Hook Form para controle de formulários',",
              "    'Arquitetura monorepo para organização do código',",
              "    'Internacionalização com i18next',",
              '  ],',
              '};',
            ],
          },
          {
            id: 'madeiramadeira',
            label: 'madeiramadeira.ts',
            content: [
              'const madeiraMadeira = {',
              "  company: 'MadeiraMadeira Comércio Eletrônico',",
              "  role: 'Mid-level Systems Analyst',",
              "  period: '03/2022 – 08/2022',",
              "  stack: ['Micro front-ends', 'Hotjar'],",
              '  highlights: [',
              "    'Arquitetura de micro front-ends',",
              "    'Migração de sistema legado para MFE',",
              "    'Análise de comportamento com Hotjar',",
              "    'Suporte técnico a desenvolvedores júnior',",
              '  ],',
              '};',
            ],
          },
          {
            id: 'softdesign',
            label: 'softdesign.ts',
            content: [
              'const softdesign = {',
              "  company: 'Softdesign Consultoria e Sistemas',",
              "  role: 'Mid-level Front-end Developer',",
              "  period: '12/2019 – 03/2022',",
              "  project: 'Novo core digital do Sicredi',",
              "  stack: ['React', 'Micro front-ends', 'Salesforce CRM', 'Scrum', 'Design System'],",
              '  highlights: [',
              "    'React em sistema crítico bancário',",
              "    'Arquitetura de micro front-ends em escala',",
              "    'Integração com Salesforce CRM',",
              "    'Uso de Design System e boas práticas de UI',",
              "    'Metodologia ágil com Scrum',",
              '  ],',
              '};',
            ],
          },
          {
            id: 'sequor',
            label: 'sequor.ts',
            content: [
              'const sequor = {',
              "  company: 'Sequor Sistemas para Automação Industrial',",
              "  role: 'Junior Developer',",
              "  period: '06/2018 – 12/2019',",
              "  stack: ['React.js', 'React Native', 'Node.js', 'MongoDB', 'REST APIs'],",
              '  highlights: [',
              "    'APIs REST com Node.js',",
              "    'Frontend com React.js',",
              "    'Aplicação mobile com React Native',",
              "    'Banco de dados MongoDB',",
              "    'Atuação full stack',",
              '  ],',
              '};',
            ],
          },
        ],
      },
    ],
  },
];

// ─── Hobbies ─────────────────────────────────────────────────────────────────

export const hobbiesTree: TreeNode[] = [
  {
    id: 'hobbies',
    label: 'hobbies',
    children: [
      {
        id: 'gaming',
        label: 'gaming',
        children: [
          {
            id: 'gaming-ts',
            label: 'gaming.ts',
            content: [
              'const gaming = {',
              "  platform: 'PC',",
              "  style: 'casual and immersive',",
              '  favoriteGenres: [',
              "    'RPG',",
              "    'strategy',",
              "    'simulation',",
              "    'sandbox',",
              "    'adventure',",
              '  ],',
              '  favoriteGames: [',
              "    'Fortnite',",
              "    'Stardew Valley',",
              "    'Grand Theft Auto (GTA)',",
              "    'Final Fantasy',",
              "    'Empire Earth',",
              "    'Harvest-moon',",
              "    'The Elder Scrolls V: Skyrim',",
              '  ],',
              "  notes: 'Tenho uma relação antiga com jogos e gosto de experiências mais tranquilas e imersivas.',",
              '};',
            ],
          },
        ],
      },
      {
        id: 'content-creation',
        label: 'content-creation',
        children: [
          {
            id: 'content-creation-ts',
            label: 'content-creation.ts',
            content: [
              'const contentCreation = {',
              "  platform: 'Twitch',",
              "  channel: 'whisperingpixels',",
              "  format: 'silent gameplay',",
              '  focus: [',
              "    'calm gameplay',",
              "    'immersive atmosphere',",
              "    'cozy and quiet content',",
              '  ],',
              "  notes: 'Tenho interesse em criar conteúdo de gameplay silencioso, com foco em uma experiência mais calma e contemplativa.',",
              '};',
            ],
          },
        ],
      },
      {
        id: 'technology',
        label: 'technology',
        children: [
          {
            id: 'technology-ts',
            label: 'technology.ts',
            content: [
              'const technology = {',
              '  interests: [',
              "    'software development',",
              "    'frontend architecture',",
              "    'performance',",
              "    'game development',",
              '  ],',
              "  notes: 'Além do trabalho com desenvolvimento, também tenho interesse em tecnologia como área de estudo e possível aproximação com o universo de jogos.',",
              '};',
            ],
          },
        ],
      },
    ],
  },
];

// ─── Code Snippets ────────────────────────────────────────────────────────────

export const codeTree: TreeNode[] = [
  {
    id: 'code-snippets',
    label: 'code-snippets',
    children: [
      {
        id: 'snippet-01',
        label: 'snippet-01.ts',
        content: [
          '// useDebounce — debounce a value to avoid excessive updates',
          '',
          'function useDebounce<T>(value: T, delay: number): T {',
          '  const [debouncedValue, setDebouncedValue] = useState<T>(value);',
          '',
          '  useEffect(() => {',
          '    const timeout = setTimeout(() => {',
          '      setDebouncedValue(value);',
          '    }, delay);',
          '',
          '    return () => clearTimeout(timeout);',
          '  }, [value, delay]);',
          '',
          '  return debouncedValue;',
          '}',
        ],
      },
      {
        id: 'snippet-02',
        label: 'snippet-02.ts',
        content: [
          '// fetchJson — typed API request with error handling',
          '',
          'async function fetchJson<T>(url: string, init?: RequestInit): Promise<T> {',
          '  const response = await fetch(url, init);',
          '',
          '  if (!response.ok) {',
          '    throw new Error(`Request failed with status ${response.status}`);',
          '  }',
          '',
          '  return response.json() as Promise<T>;',
          '}',
        ],
      },
      {
        id: 'snippet-03',
        label: 'snippet-03.ts',
        content: [
          '// formatCurrency — helper for consistent BRL formatting',
          '',
          'function formatCurrency(value: number): string {',
          "  return new Intl.NumberFormat('pt-BR', {",
          "    style: 'currency',",
          "    currency: 'BRL',",
          '  }).format(value);',
          '}',
          '',
          '// usage',
          'const price = formatCurrency(129.9);',
        ],
      },
    ],
  },
];
