export type Project = {
  id: string;
  title: string;
  description: string;
  tags: string[];
  href?: string;
  image?: string;
};

export const projects: Project[] = [
  {
    id: 'project-1',
    title: 'portfolio',
    description: 'Portfolio pessoal desenvolvido com Next.js e SCSS, com navegação responsiva e animações.',
    tags: ['next.js', 'typescript', 'scss'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-2',
    title: 'dashboard-ui',
    description: 'Dashboard administrativo com gráficos interativos e gerenciamento de dados em tempo real.',
    tags: ['react', 'typescript', 'tailwind'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-3',
    title: 'snake-game',
    description: 'Clássico jogo da cobrinha implementado com Canvas API e JavaScript puro.',
    tags: ['javascript', 'canvas'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-4',
    title: 'rest-api',
    description: 'API RESTful com autenticação JWT, rate limiting e documentação Swagger.',
    tags: ['node.js', 'typescript', 'postgresql'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-5',
    title: 'ecommerce-app',
    description: 'Aplicação de e-commerce full-stack com carrinho, checkout e painel de administração.',
    tags: ['next.js', 'prisma', 'postgresql'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-6',
    title: 'chat-realtime',
    description: 'Chat em tempo real com suporte a salas, mensagens privadas e notificações.',
    tags: ['react', 'node.js', 'mongodb'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-7',
    title: 'cli-tool',
    description: 'Ferramenta de linha de comando para automação de tarefas de desenvolvimento e deploy.',
    tags: ['go', 'docker'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-8',
    title: 'blog-platform',
    description: 'Plataforma de blog com editor markdown, tags, busca full-text e RSS feed.',
    tags: ['next.js', 'typescript', 'postgresql'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-9',
    title: 'design-system',
    description: 'Sistema de design com componentes reutilizáveis, tokens de estilo e documentação Storybook.',
    tags: ['react', 'typescript', 'scss'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-10',
    title: 'data-pipeline',
    description: 'Pipeline de processamento de dados com transformações, validações e exportação em lote.',
    tags: ['python', 'docker', 'mongodb'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-11',
    title: 'mobile-tracker',
    description: 'App de rastreamento de hábitos com gráficos de progresso e notificações diárias.',
    tags: ['react', 'typescript', 'tailwind'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-12',
    title: 'auth-service',
    description: 'Microserviço de autenticação com OAuth2, refresh tokens e auditoria de acessos.',
    tags: ['node.js', 'typescript', 'prisma'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-13',
    title: 'image-editor',
    description: 'Editor de imagens no browser com filtros, recorte e exportação via Canvas API.',
    tags: ['javascript', 'canvas', 'css'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-14',
    title: 'kanban-board',
    description: 'Board Kanban com drag-and-drop, colunas customizáveis e persistência em banco.',
    tags: ['react', 'typescript', 'postgresql'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-15',
    title: 'url-shortener',
    description: 'Encurtador de URLs com analytics de cliques, QR code e expiração configurável.',
    tags: ['go', 'postgresql'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-16',
    title: 'invoice-generator',
    description: 'Gerador de faturas em PDF com templates personalizáveis e envio automático por e-mail.',
    tags: ['node.js', 'typescript'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-17',
    title: 'weather-app',
    description: 'App de previsão do tempo com geolocalização, alertas e histórico de temperatura.',
    tags: ['react', 'typescript', 'tailwind'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-18',
    title: 'file-storage',
    description: 'Serviço de armazenamento de arquivos com upload, compressão e CDN integrado.',
    tags: ['go', 'docker', 'mongodb'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-19',
    title: 'quiz-platform',
    description: 'Plataforma de quizzes interativos com timer, ranking e relatórios de desempenho.',
    tags: ['next.js', 'typescript', 'postgresql'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-20',
    title: 'scraper-bot',
    description: 'Bot de scraping com agendamento, parsing de HTML e exportação para CSV/JSON.',
    tags: ['python', 'mongodb'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-21',
    title: 'notification-service',
    description: 'Serviço de notificações multi-canal: e-mail, push e SMS com templates dinâmicos.',
    tags: ['node.js', 'typescript', 'docker'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-22',
    title: 'code-snippet-hub',
    description: 'Hub de snippets de código com syntax highlighting, tags e busca por linguagem.',
    tags: ['next.js', 'typescript', 'prisma'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-23',
    title: 'expense-tracker',
    description: 'Rastreador de despesas com categorias, metas mensais e exportação para planilha.',
    tags: ['react', 'typescript', 'postgresql'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-24',
    title: 'markdown-editor',
    description: 'Editor markdown com preview ao vivo, temas e exportação para HTML e PDF.',
    tags: ['react', 'javascript', 'scss'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-25',
    title: 'booking-system',
    description: 'Sistema de reservas com calendário interativo, pagamento integrado e confirmação por e-mail.',
    tags: ['next.js', 'prisma', 'postgresql'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-26',
    title: 'log-analyzer',
    description: 'Analisador de logs com detecção de anomalias, dashboards e alertas em tempo real.',
    tags: ['python', 'docker', 'mongodb'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-27',
    title: 'component-library',
    description: 'Biblioteca de componentes React publicada no npm com testes e documentação interativa.',
    tags: ['react', 'typescript', 'scss'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-28',
    title: 'video-platform',
    description: 'Plataforma de vídeos com upload, transcodificação, player customizado e comentários.',
    tags: ['next.js', 'node.js', 'mongodb'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-29',
    title: 'task-automator',
    description: 'Automatizador de tarefas repetitivas com agendamento cron e relatórios de execução.',
    tags: ['python', 'docker'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-30',
    title: 'forum-app',
    description: 'Fórum com threads, votação, moderação e sistema de reputação para usuários.',
    tags: ['next.js', 'typescript', 'postgresql'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-31',
    title: 'map-explorer',
    description: 'Explorador de mapas interativos com camadas, filtros e geolocalização de pontos de interesse.',
    tags: ['react', 'typescript', 'tailwind'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-32',
    title: 'rate-limiter',
    description: 'Middleware de rate limiting com algoritmo token bucket e armazenamento distribuído.',
    tags: ['go', 'docker'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-33',
    title: 'form-builder',
    description: 'Builder visual de formulários com validação configurável, lógica condicional e webhooks.',
    tags: ['react', 'typescript', 'tailwind'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-34',
    title: 'recipe-app',
    description: 'App de receitas com busca por ingredientes, plano alimentar semanal e lista de compras.',
    tags: ['next.js', 'typescript', 'prisma'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-35',
    title: 'load-balancer',
    description: 'Load balancer em Go com health check, round-robin e suporte a sticky sessions.',
    tags: ['go', 'docker'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-36',
    title: 'social-feed',
    description: 'Feed social com posts, reações, comentários aninhados e timeline personalizada.',
    tags: ['react', 'node.js', 'mongodb'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-37',
    title: 'ci-dashboard',
    description: 'Dashboard de integração contínua com status de builds, métricas e histórico de deploys.',
    tags: ['react', 'typescript', 'docker'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-38',
    title: 'pixel-art-editor',
    description: 'Editor de pixel art com paleta de cores, frames de animação e exportação GIF.',
    tags: ['javascript', 'canvas', 'css'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-39',
    title: 'cms-headless',
    description: 'CMS headless com API GraphQL, versionamento de conteúdo e preview ao vivo.',
    tags: ['node.js', 'typescript', 'mongodb'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-40',
    title: 'music-player',
    description: 'Player de música com equalizer via Web Audio API, playlists e visualizador de frequências.',
    tags: ['javascript', 'canvas', 'scss'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-41',
    title: 'event-sourcing',
    description: 'Implementação de event sourcing com CQRS, projeções e replay de eventos históricos.',
    tags: ['go', 'postgresql', 'docker'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-42',
    title: 'landing-builder',
    description: 'Builder de landing pages com blocos drag-and-drop, temas e publicação com um clique.',
    tags: ['react', 'typescript', 'tailwind'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-43',
    title: 'pdf-toolkit',
    description: 'Toolkit para manipulação de PDFs: merge, split, compressão e extração de texto.',
    tags: ['python', 'docker'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-44',
    title: 'job-scheduler',
    description: 'Agendador de jobs distribuído com prioridade, retry automático e monitoramento.',
    tags: ['go', 'postgresql', 'docker'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-45',
    title: 'typing-game',
    description: 'Jogo de digitação com níveis de dificuldade, estatísticas de WPM e ranking global.',
    tags: ['javascript', 'css'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-46',
    title: 'inventory-manager',
    description: 'Sistema de gestão de estoque com alertas de reposição, histórico e relatórios em PDF.',
    tags: ['next.js', 'prisma', 'postgresql'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-47',
    title: 'graph-visualizer',
    description: 'Visualizador de grafos com algoritmos de BFS, DFS e Dijkstra animados em Canvas.',
    tags: ['javascript', 'canvas', 'tailwind'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-48',
    title: 'search-engine',
    description: 'Motor de busca com índice invertido, relevância por TF-IDF e sugestões de autocomplete.',
    tags: ['python', 'postgresql'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-49',
    title: 'survey-tool',
    description: 'Ferramenta de pesquisas com múltiplos tipos de pergunta, análise de respostas e exportação.',
    tags: ['next.js', 'typescript', 'mongodb'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-50',
    title: 'terminal-ui',
    description: 'Interface de terminal no browser com suporte a múltiplas abas, temas e histórico.',
    tags: ['react', 'typescript', 'scss'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-51',
    title: 'proxy-server',
    description: 'Servidor proxy reverso com cache, compressão gzip e suporte a WebSockets.',
    tags: ['go', 'docker'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-52',
    title: 'fitness-tracker',
    description: 'Tracker de treinos com histórico de exercícios, gráficos de evolução e metas semanais.',
    tags: ['react', 'typescript', 'prisma'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-53',
    title: 'theme-generator',
    description: 'Gerador de temas CSS com paleta de cores, preview ao vivo e exportação de variáveis.',
    tags: ['javascript', 'css', 'scss'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-54',
    title: 'webhook-hub',
    description: 'Hub de webhooks com roteamento, retry, logs de entrega e painel de inspeção.',
    tags: ['node.js', 'typescript', 'postgresql'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-55',
    title: 'notes-app',
    description: 'App de notas com editor rich text, organização por pastas e sincronização offline.',
    tags: ['react', 'typescript', 'mongodb'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-56',
    title: 'container-orchestrator',
    description: 'Orquestrador de containers simplificado com deploy, scaling e health checks automáticos.',
    tags: ['go', 'docker'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-57',
    title: 'spreadsheet-engine',
    description: 'Motor de planilhas com fórmulas, referências entre células e gráficos dinâmicos.',
    tags: ['typescript', 'canvas', 'react'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-58',
    title: 'ai-prompt-manager',
    description: 'Gerenciador de prompts de IA com versionamento, testes A/B e análise de resultados.',
    tags: ['next.js', 'typescript', 'postgresql'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-59',
    title: 'event-calendar',
    description: 'Calendário de eventos com visualizações diária, semanal e mensal, convites e recorrência.',
    tags: ['react', 'typescript', 'prisma'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-60',
    title: 'migration-runner',
    description: 'Runner de migrations de banco de dados com rollback, dry-run e versionamento semântico.',
    tags: ['go', 'postgresql'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-61',
    title: 'virtual-whiteboard',
    description: 'Quadro branco virtual com desenho colaborativo em tempo real, formas e sticky notes.',
    tags: ['javascript', 'canvas', 'node.js'],
    href: 'https://github.com/thiagoborba',
  },
  {
    id: 'project-62',
    title: 'config-manager',
    description: 'Gerenciador de configurações de aplicações com ambientes, secrets e auditoria de mudanças.',
    tags: ['go', 'docker', 'postgresql'],
    href: 'https://github.com/thiagoborba',
  },
];
